title: TORCHLITE Documentation
description: Documentation for the TORCHLITE dashboard
theme: just-the-docs
color_scheme: htrc

url: htrc.github.io/torchlite-documentation/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
