title: TORCHLITE documentation
description: Documentation on how to use the TORCHLITE dashboard.
theme: just-the-docs
color_scheme: htrc

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
